import { TechCategory, TechId } from "@/enums";

export const SKILL_ICONS_URL = "https://skillicons.dev";

export interface TechSchema {
  id: TechId;
  name: string;
  category: TechCategory;
}
export const TECH_LIST: TechSchema[] = [
  { id: TechId.Ableton, name: "Ableton Live", category: TechCategory.Other },
  { id: TechId.ActivityPub, name: "ActivityPub", category: TechCategory.Other },
  { id: TechId.Actix, name: "Actix", category: TechCategory.Framework },
  { id: TechId.Adonis, name: "AdonisJS", category: TechCategory.Framework },
  { id: TechId.Ae, name: "Adobe After Effects", category: TechCategory.Other },
  { id: TechId.AiScript, name: "AI Script", category: TechCategory.Other },
  { id: TechId.AlpineJs, name: "Alpine.js", category: TechCategory.Framework },
  { id: TechId.Anaconda, name: "Anaconda", category: TechCategory.Platform },
  {
    id: TechId.AndroidStudio,
    name: "Android Studio",
    category: TechCategory.Platform,
  },
  { id: TechId.Angular, name: "Angular", category: TechCategory.Framework },
  { id: TechId.Ansible, name: "Ansible", category: TechCategory.Platform },
  { id: TechId.Apollo, name: "Apollo GraphQL", category: TechCategory.Library },
  { id: TechId.Apple, name: "Apple", category: TechCategory.Platform },
  { id: TechId.Appwrite, name: "Appwrite", category: TechCategory.Cloud },
  { id: TechId.Arch, name: "Arch Linux", category: TechCategory.Platform },
  { id: TechId.Arduino, name: "Arduino", category: TechCategory.Platform },
  { id: TechId.Astro, name: "Astro", category: TechCategory.Framework },
  { id: TechId.Atom, name: "Atom", category: TechCategory.Platform },
  { id: TechId.Au, name: "AU (Audio Units)", category: TechCategory.Other },
  { id: TechId.AutoCAD, name: "AutoCAD", category: TechCategory.Other },
  { id: TechId.Aws, name: "Amazon Web Services", category: TechCategory.Cloud },
  { id: TechId.Azul, name: "Azul Systems", category: TechCategory.Platform },
  { id: TechId.Azure, name: "Microsoft Azure", category: TechCategory.Cloud },
  { id: TechId.Babel, name: "Babel", category: TechCategory.Library },
  { id: TechId.Bash, name: "Bash", category: TechCategory.Language },
  { id: TechId.Bevy, name: "Bevy", category: TechCategory.Framework },
  { id: TechId.Bitbucket, name: "Bitbucket", category: TechCategory.CICD },
  { id: TechId.Blender, name: "Blender", category: TechCategory.Other },
  { id: TechId.Bootstrap, name: "Bootstrap", category: TechCategory.Library },
  { id: TechId.Bsd, name: "BSD", category: TechCategory.Platform },
  { id: TechId.Bun, name: "Bun", category: TechCategory.Platform },
  { id: TechId.C, name: "C", category: TechCategory.Language },
  { id: TechId.Cs, name: "C#", category: TechCategory.Language },
  { id: TechId.Cpp, name: "C++", category: TechCategory.Language },
  { id: TechId.Crystal, name: "Crystal", category: TechCategory.Language },
  {
    id: TechId.Cassandra,
    name: "Apache Cassandra",
    category: TechCategory.Database,
  },
  { id: TechId.Clion, name: "CLion", category: TechCategory.Platform },
  { id: TechId.Clojure, name: "Clojure", category: TechCategory.Language },
  { id: TechId.Cloudflare, name: "Cloudflare", category: TechCategory.Cloud },
  { id: TechId.CMake, name: "CMake", category: TechCategory.Library },
  { id: TechId.Codepen, name: "CodePen", category: TechCategory.Platform },
  {
    id: TechId.CoffeeScript,
    name: "CoffeeScript",
    category: TechCategory.Language,
  },
  {
    id: TechId.Css,
    name: "CSS",
    category: TechCategory.Language,
  },
  { id: TechId.Cypress, name: "Cypress", category: TechCategory.Library },
  { id: TechId.D3, name: "D3.js", category: TechCategory.Library },
  { id: TechId.Dart, name: "Dart", category: TechCategory.Language },
  { id: TechId.Debian, name: "Debian", category: TechCategory.Platform },
  { id: TechId.Deno, name: "Deno", category: TechCategory.Platform },
  { id: TechId.DevTo, name: "DEV Community", category: TechCategory.Other },
  { id: TechId.Discord, name: "Discord", category: TechCategory.Other },
  { id: TechId.Bots, name: "Discord Bots", category: TechCategory.Other },
  { id: TechId.DiscordJs, name: "Discord.js", category: TechCategory.Library },
  { id: TechId.Django, name: "Django", category: TechCategory.Framework },
  { id: TechId.Docker, name: "Docker", category: TechCategory.Platform },
  { id: TechId.Dotnet, name: ".NET", category: TechCategory.Framework },
  {
    id: TechId.DynamoDB,
    name: "Amazon DynamoDB",
    category: TechCategory.Database,
  },
  { id: TechId.Eclipse, name: "Eclipse", category: TechCategory.Platform },
  {
    id: TechId.Elasticsearch,
    name: "Elasticsearch",
    category: TechCategory.Database,
  },
  { id: TechId.Electron, name: "Electron", category: TechCategory.Framework },
  { id: TechId.Elixir, name: "Elixir", category: TechCategory.Language },
  { id: TechId.Elysia, name: "Elysia", category: TechCategory.Framework },
  { id: TechId.Emacs, name: "GNU Emacs", category: TechCategory.Platform },
  { id: TechId.Ember, name: "Ember.js", category: TechCategory.Framework },
  { id: TechId.Emotion, name: "Emotion", category: TechCategory.Library },
  { id: TechId.Express, name: "Express.js", category: TechCategory.Framework },
  { id: TechId.FastAPI, name: "FastAPI", category: TechCategory.Framework },
  { id: TechId.Fediverse, name: "Fediverse", category: TechCategory.Other },
  { id: TechId.Figma, name: "Figma", category: TechCategory.Other },
  { id: TechId.Firebase, name: "Firebase", category: TechCategory.Cloud },
  { id: TechId.Flask, name: "Flask", category: TechCategory.Framework },
  { id: TechId.Flutter, name: "Flutter", category: TechCategory.Framework },
  { id: TechId.Forth, name: "Forth", category: TechCategory.Language },
  { id: TechId.Fortran, name: "Fortran", category: TechCategory.Language },
  {
    id: TechId.GameMakerStudio,
    name: "GameMaker Studio",
    category: TechCategory.Platform,
  },
  { id: TechId.Gatsby, name: "Gatsby", category: TechCategory.Framework },
  {
    id: TechId.Gcp,
    name: "Google Cloud Platform",
    category: TechCategory.Cloud,
  },
  { id: TechId.Git, name: "Git", category: TechCategory.Other },
  { id: TechId.Github, name: "GitHub", category: TechCategory.Other },
  {
    id: TechId.GithubActions,
    name: "GitHub Actions",
    category: TechCategory.CICD,
  },
  { id: TechId.Gitlab, name: "GitLab", category: TechCategory.Other },
  { id: TechId.Gmail, name: "Gmail", category: TechCategory.Other },
  { id: TechId.Gherkin, name: "Gherkin", category: TechCategory.Language },
  { id: TechId.Go, name: "Go", category: TechCategory.Language },
  { id: TechId.Gradle, name: "Gradle", category: TechCategory.BuildTool },
  { id: TechId.Godot, name: "Godot Engine", category: TechCategory.Platform },
  { id: TechId.Grafana, name: "Grafana", category: TechCategory.Other },
  { id: TechId.GraphQL, name: "GraphQL", category: TechCategory.Language },
  { id: TechId.Gtk, name: "GTK", category: TechCategory.Framework },
  { id: TechId.Gulp, name: "Gulp", category: TechCategory.BuildTool },
  { id: TechId.Haskell, name: "Haskell", category: TechCategory.Language },
  { id: TechId.Haxe, name: "Haxe", category: TechCategory.Language },
  {
    id: TechId.HaxeFlixel,
    name: "HaxeFlixel",
    category: TechCategory.Framework,
  },
  { id: TechId.Heroku, name: "Heroku", category: TechCategory.Cloud },
  { id: TechId.Hibernate, name: "Hibernate", category: TechCategory.Framework },
  {
    id: TechId.Html,
    name: "HTML",
    category: TechCategory.Language,
  },
  { id: TechId.Htmx, name: "htmx", category: TechCategory.Framework },
  { id: TechId.Idea, name: "IntelliJ IDEA", category: TechCategory.Platform },
  {
    id: TechId.Ai,
    name: "Artificial Intelligence (AI)",
    category: TechCategory.Other,
  },
  { id: TechId.Instagram, name: "Instagram", category: TechCategory.Other },
  {
    id: TechId.Ipfs,
    name: "InterPlanetary File System (IPFS)",
    category: TechCategory.Other,
  },
  { id: TechId.Java, name: "Java", category: TechCategory.Language },
  { id: TechId.Js, name: "JavaScript", category: TechCategory.Language },
  { id: TechId.Jenkins, name: "Jenkins", category: TechCategory.CICD },
  { id: TechId.Jest, name: "Jest", category: TechCategory.Other },
  { id: TechId.Jquery, name: "jQuery", category: TechCategory.Library },
  { id: TechId.Kafka, name: "Apache Kafka", category: TechCategory.Other },
  { id: TechId.Kali, name: "Kali Linux", category: TechCategory.Platform },
  { id: TechId.Kotlin, name: "Kotlin", category: TechCategory.Language },
  { id: TechId.Ktor, name: "Ktor", category: TechCategory.Framework },
  { id: TechId.Kubernetes, name: "Kubernetes", category: TechCategory.Other },
  { id: TechId.Laravel, name: "Laravel", category: TechCategory.Framework },
  { id: TechId.Latex, name: "LaTeX", category: TechCategory.Other },
  { id: TechId.Less, name: "LESS", category: TechCategory.Language },
  { id: TechId.Linkedin, name: "LinkedIn", category: TechCategory.Other },
  { id: TechId.Linux, name: "Linux", category: TechCategory.Platform },
  { id: TechId.Lit, name: "Lit", category: TechCategory.Framework },
  { id: TechId.Lua, name: "Lua", category: TechCategory.Language },
  { id: TechId.Md, name: "Markdown (MD)", category: TechCategory.Language },
  { id: TechId.Mastodon, name: "Mastodon", category: TechCategory.Other },
  {
    id: TechId.MaterialUI,
    name: "Material-UI",
    category: TechCategory.Library,
  },
  { id: TechId.Matlab, name: "MATLAB", category: TechCategory.Language },
  { id: TechId.Maven, name: "Apache Maven", category: TechCategory.BuildTool },
  { id: TechId.Mint, name: "Mint", category: TechCategory.Platform },
  { id: TechId.Misskey, name: "Misskey", category: TechCategory.Other },
  { id: TechId.MongoDB, name: "MongoDB", category: TechCategory.Database },
  { id: TechId.MySQL, name: "MySQL", category: TechCategory.Database },
  { id: TechId.Neovim, name: "Neovim", category: TechCategory.Platform },
  { id: TechId.NestJS, name: "NestJS", category: TechCategory.Framework },
  { id: TechId.Netlify, name: "Netlify", category: TechCategory.Cloud },
  { id: TechId.NextJS, name: "Next.js", category: TechCategory.Framework },
  { id: TechId.Nginx, name: "NGINX", category: TechCategory.Other },
  { id: TechId.Nim, name: "Nim", category: TechCategory.Language },
  { id: TechId.Nix, name: "Nix", category: TechCategory.Platform },
  { id: TechId.NodeJS, name: "Node.js", category: TechCategory.Platform },
  { id: TechId.Notion, name: "Notion", category: TechCategory.Other },
  { id: TechId.Npm, name: "npm", category: TechCategory.BuildTool },
  { id: TechId.NuxtJS, name: "Nuxt.js", category: TechCategory.Framework },
  { id: TechId.Obsidian, name: "Obsidian", category: TechCategory.Other },
  { id: TechId.Ocaml, name: "OCaml", category: TechCategory.Language },
  { id: TechId.Octave, name: "GNU Octave", category: TechCategory.Language },
  { id: TechId.OpenCV, name: "OpenCV", category: TechCategory.Library },
  { id: TechId.OpenShift, name: "OpenShift", category: TechCategory.Cloud },
  { id: TechId.OpenStack, name: "OpenStack", category: TechCategory.Cloud },
  { id: TechId.P5Js, name: "p5.js", category: TechCategory.Library },
  { id: TechId.Perl, name: "Perl", category: TechCategory.Language },
  {
    id: TechId.PowerShell,
    name: "PowerShell",
    category: TechCategory.Language,
  },
  { id: TechId.Php, name: "PHP", category: TechCategory.Language },
  { id: TechId.PhpStorm, name: "PhpStorm", category: TechCategory.Platform },
  { id: TechId.Pinia, name: "Pinia", category: TechCategory.Library },
  { id: TechId.Pkl, name: "PKL", category: TechCategory.Other },
  { id: TechId.Plan9, name: "Plan 9", category: TechCategory.Platform },
  {
    id: TechId.PlanetScale,
    name: "PlanetScale",
    category: TechCategory.Database,
  },
  { id: TechId.Pnpm, name: "pnpm", category: TechCategory.Other },
  { id: TechId.Postgres, name: "PostgreSQL", category: TechCategory.Database },
  { id: TechId.Postman, name: "Postman", category: TechCategory.Other },
  { id: TechId.Ps, name: "Adobe PhotoShop", category: TechCategory.Other },
  { id: TechId.Pr, name: "Adobe Premiere Pro", category: TechCategory.Other },
  { id: TechId.Prisma, name: "Prisma", category: TechCategory.Library },
  {
    id: TechId.Processing,
    name: "Processing",
    category: TechCategory.Language,
  },
  { id: TechId.Prometheus, name: "Prometheus", category: TechCategory.Other },
  { id: TechId.Pug, name: "Pug", category: TechCategory.Language },
  { id: TechId.PyCharm, name: "PyCharm", category: TechCategory.Platform },
  { id: TechId.Py, name: "Python", category: TechCategory.Language },
  { id: TechId.PyTorch, name: "PyTorch", category: TechCategory.Library },
  { id: TechId.Qt, name: "Qt", category: TechCategory.Framework },
  { id: TechId.R, name: "R", category: TechCategory.Language },
  { id: TechId.RabbitMQ, name: "RabbitMQ", category: TechCategory.Other },
  { id: TechId.Rails, name: "Ruby on Rails", category: TechCategory.Framework },
  {
    id: TechId.RaspberryPi,
    name: "Raspberry Pi",
    category: TechCategory.Other,
  },
  { id: TechId.React, name: "React", category: TechCategory.Framework },
  { id: TechId.ReactiveX, name: "ReactiveX", category: TechCategory.Library },
  { id: TechId.RedHat, name: "Red Hat", category: TechCategory.Platform },
  { id: TechId.Redis, name: "Redis", category: TechCategory.Database },
  { id: TechId.Redux, name: "Redux", category: TechCategory.Library },
  {
    id: TechId.Regex,
    name: "Regular Expressions (Regex)",
    category: TechCategory.Other,
  },
  { id: TechId.Remix, name: "Remix", category: TechCategory.Framework },
  { id: TechId.Replit, name: "Replit", category: TechCategory.Platform },
  {
    id: TechId.Rider,
    name: "JetBrains Rider",
    category: TechCategory.Platform,
  },
  {
    id: TechId.RobloxStudio,
    name: "Roblox Studio",
    category: TechCategory.Platform,
  },
  { id: TechId.Rocket, name: "Rocket", category: TechCategory.Framework },
  { id: TechId.RollupJS, name: "Rollup.js", category: TechCategory.BuildTool },
  {
    id: TechId.Ros,
    name: "Robot Operating System (ROS)",
    category: TechCategory.Platform,
  },
  { id: TechId.Ruby, name: "Ruby", category: TechCategory.Language },
  { id: TechId.Rust, name: "Rust", category: TechCategory.Language },
  { id: TechId.Sass, name: "Sass", category: TechCategory.Language },
  {
    id: TechId.Spring,
    name: "Spring Framework",
    category: TechCategory.Framework,
  },
  { id: TechId.Sqlite, name: "SQLite", category: TechCategory.Database },
  {
    id: TechId.StackOverflow,
    name: "Stack Overflow",
    category: TechCategory.Other,
  },
  {
    id: TechId.StyledComponents,
    name: "Styled Components",
    category: TechCategory.Library,
  },
  { id: TechId.Sublime, name: "Sublime Text", category: TechCategory.Platform },
  { id: TechId.Supabase, name: "Supabase", category: TechCategory.Database },
  { id: TechId.Scala, name: "Scala", category: TechCategory.Language },
  { id: TechId.Sklearn, name: "scikit-learn", category: TechCategory.Library },
  { id: TechId.Selenium, name: "Selenium", category: TechCategory.Library },
  { id: TechId.Sentry, name: "Sentry", category: TechCategory.Other },
  { id: TechId.Sequelize, name: "Sequelize", category: TechCategory.Library },
  { id: TechId.SketchUp, name: "SketchUp", category: TechCategory.Platform },
  { id: TechId.Solidity, name: "Solidity", category: TechCategory.Language },
  { id: TechId.SolidJS, name: "SolidJS", category: TechCategory.Framework },
  { id: TechId.Svelte, name: "Svelte", category: TechCategory.Framework },
  {
    id: TechId.Svg,
    name: "SVG (Scalable Vector Graphics)",
    category: TechCategory.Other,
  },
  { id: TechId.Swift, name: "Swift", category: TechCategory.Language },
  { id: TechId.Symfony, name: "Symfony", category: TechCategory.Framework },
  { id: TechId.Tailwind, name: "Tailwind CSS", category: TechCategory.Library },
  { id: TechId.Tauri, name: "Tauri", category: TechCategory.Platform },
  { id: TechId.TensorFlow, name: "TensorFlow", category: TechCategory.Library },
  { id: TechId.Terraform, name: "Terraform", category: TechCategory.Other },
  { id: TechId.ThreeJS, name: "Three.js", category: TechCategory.Library },
  { id: TechId.Twitter, name: "Twitter", category: TechCategory.Other },
  { id: TechId.Ts, name: "TypeScript", category: TechCategory.Language },
  { id: TechId.Ubuntu, name: "Ubuntu", category: TechCategory.Platform },
  { id: TechId.Unity, name: "Unity", category: TechCategory.Platform },
  { id: TechId.Unreal, name: "Unreal Engine", category: TechCategory.Other },
  { id: TechId.V, name: "V", category: TechCategory.Language },
  { id: TechId.Vala, name: "Vala", category: TechCategory.Language },
  { id: TechId.Vercel, name: "Vercel", category: TechCategory.Platform },
  { id: TechId.Vim, name: "Vim", category: TechCategory.Other },
  {
    id: TechId.VisualStudio,
    name: "Visual Studio",
    category: TechCategory.Platform,
  },
  { id: TechId.Vite, name: "Vite", category: TechCategory.BuildTool },
  { id: TechId.Vitest, name: "Vitest", category: TechCategory.Other },
  {
    id: TechId.Vscode,
    name: "Visual Studio Code",
    category: TechCategory.Other,
  },
  { id: TechId.Vscodium, name: "VSCodium", category: TechCategory.Other },
  { id: TechId.Vue, name: "Vue.js", category: TechCategory.Framework },
  { id: TechId.Vuetify, name: "Vuetify", category: TechCategory.Library },
  { id: TechId.Wasm, name: "WebAssembly (WASM)", category: TechCategory.Other },
  { id: TechId.Webflow, name: "Webflow", category: TechCategory.Platform },
  { id: TechId.Webpack, name: "Webpack", category: TechCategory.BuildTool },
  { id: TechId.WebStorm, name: "WebStorm", category: TechCategory.Platform },
  { id: TechId.WindiCSS, name: "Windi CSS", category: TechCategory.Library },
  { id: TechId.Windows, name: "Windows", category: TechCategory.Platform },
  { id: TechId.WordPress, name: "WordPress", category: TechCategory.Other },
  { id: TechId.Workers, name: "Workers", category: TechCategory.Other },
  { id: TechId.Xd, name: "Adobe XD", category: TechCategory.Other },
  { id: TechId.Yarn, name: "Yarn", category: TechCategory.Other },
  { id: TechId.Yew, name: "Yew", category: TechCategory.Framework },
  { id: TechId.Zig, name: "Zig", category: TechCategory.Language },
];
