import { TechCategory, SkillIconsId } from "@/enums";

export const SKILL_ICONS_URL = "https://skillicons.dev";

export interface TechSchema {
  id: SkillIconsId;
  name: string;
  category: TechCategory;
}
export const SKILL_ICONS_LIST: TechSchema[] = [
  {
    id: SkillIconsId.Ableton,
    name: "Ableton Live",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.ActivityPub,
    name: "ActivityPub",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Actix, name: "Actix", category: TechCategory.Framework },
  {
    id: SkillIconsId.Adonis,
    name: "AdonisJS",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Ae,
    name: "Adobe After Effects",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.AiScript,
    name: "AI Script",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.AlpineJs,
    name: "Alpine.js",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Anaconda,
    name: "Anaconda",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.AndroidStudio,
    name: "Android Studio",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Angular,
    name: "Angular",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Ansible,
    name: "Ansible",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Apollo,
    name: "Apollo GraphQL",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Apple, name: "Apple", category: TechCategory.Platform },
  { id: SkillIconsId.Appwrite, name: "Appwrite", category: TechCategory.Cloud },
  {
    id: SkillIconsId.Arch,
    name: "Arch Linux",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Arduino,
    name: "Arduino",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Astro, name: "Astro", category: TechCategory.Framework },
  { id: SkillIconsId.Atom, name: "Atom", category: TechCategory.Platform },
  {
    id: SkillIconsId.Au,
    name: "AU (Audio Units)",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.AutoCAD, name: "AutoCAD", category: TechCategory.Other },
  {
    id: SkillIconsId.Aws,
    name: "Amazon Web Services",
    category: TechCategory.Cloud,
  },
  {
    id: SkillIconsId.Azul,
    name: "Azul Systems",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Azure,
    name: "Microsoft Azure",
    category: TechCategory.Cloud,
  },
  { id: SkillIconsId.Babel, name: "Babel", category: TechCategory.Library },
  { id: SkillIconsId.Bash, name: "Bash", category: TechCategory.Language },
  { id: SkillIconsId.Bevy, name: "Bevy", category: TechCategory.Framework },
  {
    id: SkillIconsId.Bitbucket,
    name: "Bitbucket",
    category: TechCategory.CICD,
  },
  { id: SkillIconsId.Blender, name: "Blender", category: TechCategory.Other },
  {
    id: SkillIconsId.Bootstrap,
    name: "Bootstrap",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Bsd, name: "BSD", category: TechCategory.Platform },
  { id: SkillIconsId.Bun, name: "Bun", category: TechCategory.Platform },
  { id: SkillIconsId.C, name: "C", category: TechCategory.Language },
  { id: SkillIconsId.Cs, name: "C#", category: TechCategory.Language },
  { id: SkillIconsId.Cpp, name: "C++", category: TechCategory.Language },
  {
    id: SkillIconsId.Crystal,
    name: "Crystal",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.Cassandra,
    name: "Apache Cassandra",
    category: TechCategory.Database,
  },
  { id: SkillIconsId.Clion, name: "CLion", category: TechCategory.Platform },
  {
    id: SkillIconsId.Clojure,
    name: "Clojure",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.Cloudflare,
    name: "Cloudflare",
    category: TechCategory.Cloud,
  },
  { id: SkillIconsId.CMake, name: "CMake", category: TechCategory.Library },
  {
    id: SkillIconsId.Codepen,
    name: "CodePen",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.CoffeeScript,
    name: "CoffeeScript",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.Css,
    name: "CSS",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Cypress, name: "Cypress", category: TechCategory.Library },
  { id: SkillIconsId.D3, name: "D3.js", category: TechCategory.Library },
  { id: SkillIconsId.Dart, name: "Dart", category: TechCategory.Language },
  { id: SkillIconsId.Debian, name: "Debian", category: TechCategory.Platform },
  { id: SkillIconsId.Deno, name: "Deno", category: TechCategory.Platform },
  {
    id: SkillIconsId.DevTo,
    name: "DEV Community",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Discord, name: "Discord", category: TechCategory.Other },
  { id: SkillIconsId.Bots, name: "Discord Bots", category: TechCategory.Other },
  {
    id: SkillIconsId.DiscordJs,
    name: "Discord.js",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Django, name: "Django", category: TechCategory.Framework },
  { id: SkillIconsId.Docker, name: "Docker", category: TechCategory.Platform },
  { id: SkillIconsId.Dotnet, name: ".NET", category: TechCategory.Framework },
  {
    id: SkillIconsId.DynamoDB,
    name: "Amazon DynamoDB",
    category: TechCategory.Database,
  },
  {
    id: SkillIconsId.Eclipse,
    name: "Eclipse",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Elasticsearch,
    name: "Elasticsearch",
    category: TechCategory.Database,
  },
  {
    id: SkillIconsId.Electron,
    name: "Electron",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Elixir, name: "Elixir", category: TechCategory.Language },
  { id: SkillIconsId.Elysia, name: "Elysia", category: TechCategory.Framework },
  {
    id: SkillIconsId.Emacs,
    name: "GNU Emacs",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Ember,
    name: "Ember.js",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Emotion, name: "Emotion", category: TechCategory.Library },
  {
    id: SkillIconsId.Express,
    name: "Express.js",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.FastAPI,
    name: "FastAPI",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Fediverse,
    name: "Fediverse",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Figma, name: "Figma", category: TechCategory.Other },
  { id: SkillIconsId.Firebase, name: "Firebase", category: TechCategory.Cloud },
  { id: SkillIconsId.Flask, name: "Flask", category: TechCategory.Framework },
  {
    id: SkillIconsId.Flutter,
    name: "Flutter",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Forth, name: "Forth", category: TechCategory.Language },
  {
    id: SkillIconsId.Fortran,
    name: "Fortran",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.GameMakerStudio,
    name: "GameMaker Studio",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Gatsby, name: "Gatsby", category: TechCategory.Framework },
  {
    id: SkillIconsId.Gcp,
    name: "Google Cloud Platform",
    category: TechCategory.Cloud,
  },
  { id: SkillIconsId.Git, name: "Git", category: TechCategory.Other },
  { id: SkillIconsId.Github, name: "GitHub", category: TechCategory.Other },
  {
    id: SkillIconsId.GithubActions,
    name: "GitHub Actions",
    category: TechCategory.CICD,
  },
  { id: SkillIconsId.Gitlab, name: "GitLab", category: TechCategory.Other },
  { id: SkillIconsId.Gmail, name: "Gmail", category: TechCategory.Other },
  {
    id: SkillIconsId.Gherkin,
    name: "Gherkin",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Go, name: "Go", category: TechCategory.Language },
  { id: SkillIconsId.Gradle, name: "Gradle", category: TechCategory.BuildTool },
  {
    id: SkillIconsId.Godot,
    name: "Godot Engine",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Grafana, name: "Grafana", category: TechCategory.Other },
  {
    id: SkillIconsId.GraphQL,
    name: "GraphQL",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Gtk, name: "GTK", category: TechCategory.Framework },
  { id: SkillIconsId.Gulp, name: "Gulp", category: TechCategory.BuildTool },
  {
    id: SkillIconsId.Haskell,
    name: "Haskell",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Haxe, name: "Haxe", category: TechCategory.Language },
  {
    id: SkillIconsId.HaxeFlixel,
    name: "HaxeFlixel",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Heroku, name: "Heroku", category: TechCategory.Cloud },
  {
    id: SkillIconsId.Hibernate,
    name: "Hibernate",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Html,
    name: "HTML",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Htmx, name: "htmx", category: TechCategory.Framework },
  {
    id: SkillIconsId.Idea,
    name: "IntelliJ IDEA",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Ai,
    name: "Artificial Intelligence (AI)",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Instagram,
    name: "Instagram",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Ipfs,
    name: "InterPlanetary File System (IPFS)",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Java, name: "Java", category: TechCategory.Language },
  { id: SkillIconsId.Js, name: "JavaScript", category: TechCategory.Language },
  { id: SkillIconsId.Jenkins, name: "Jenkins", category: TechCategory.CICD },
  { id: SkillIconsId.Jest, name: "Jest", category: TechCategory.Other },
  { id: SkillIconsId.Jquery, name: "jQuery", category: TechCategory.Library },
  {
    id: SkillIconsId.Kafka,
    name: "Apache Kafka",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Kali,
    name: "Kali Linux",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Kotlin, name: "Kotlin", category: TechCategory.Language },
  { id: SkillIconsId.Ktor, name: "Ktor", category: TechCategory.Framework },
  {
    id: SkillIconsId.Kubernetes,
    name: "Kubernetes",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Laravel,
    name: "Laravel",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Latex, name: "LaTeX", category: TechCategory.Other },
  { id: SkillIconsId.Less, name: "LESS", category: TechCategory.Language },
  { id: SkillIconsId.Linkedin, name: "LinkedIn", category: TechCategory.Other },
  { id: SkillIconsId.Linux, name: "Linux", category: TechCategory.Platform },
  { id: SkillIconsId.Lit, name: "Lit", category: TechCategory.Framework },
  { id: SkillIconsId.Lua, name: "Lua", category: TechCategory.Language },
  {
    id: SkillIconsId.Md,
    name: "Markdown (MD)",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Mastodon, name: "Mastodon", category: TechCategory.Other },
  {
    id: SkillIconsId.MaterialUI,
    name: "Material-UI",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Matlab, name: "MATLAB", category: TechCategory.Language },
  {
    id: SkillIconsId.Maven,
    name: "Apache Maven",
    category: TechCategory.BuildTool,
  },
  { id: SkillIconsId.Mint, name: "Mint", category: TechCategory.Platform },
  { id: SkillIconsId.Misskey, name: "Misskey", category: TechCategory.Other },
  {
    id: SkillIconsId.MongoDB,
    name: "MongoDB",
    category: TechCategory.Database,
  },
  { id: SkillIconsId.MySQL, name: "MySQL", category: TechCategory.Database },
  { id: SkillIconsId.Neovim, name: "Neovim", category: TechCategory.Platform },
  { id: SkillIconsId.NestJS, name: "NestJS", category: TechCategory.Framework },
  { id: SkillIconsId.Netlify, name: "Netlify", category: TechCategory.Cloud },
  {
    id: SkillIconsId.NextJS,
    name: "Next.js",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Nginx, name: "NGINX", category: TechCategory.Other },
  { id: SkillIconsId.Nim, name: "Nim", category: TechCategory.Language },
  { id: SkillIconsId.Nix, name: "Nix", category: TechCategory.Platform },
  { id: SkillIconsId.NodeJS, name: "Node.js", category: TechCategory.Platform },
  { id: SkillIconsId.Notion, name: "Notion", category: TechCategory.Other },
  { id: SkillIconsId.Npm, name: "npm", category: TechCategory.BuildTool },
  {
    id: SkillIconsId.NuxtJS,
    name: "Nuxt.js",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Obsidian, name: "Obsidian", category: TechCategory.Other },
  { id: SkillIconsId.Ocaml, name: "OCaml", category: TechCategory.Language },
  {
    id: SkillIconsId.Octave,
    name: "GNU Octave",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.OpenCV, name: "OpenCV", category: TechCategory.Library },
  {
    id: SkillIconsId.OpenShift,
    name: "OpenShift",
    category: TechCategory.Cloud,
  },
  {
    id: SkillIconsId.OpenStack,
    name: "OpenStack",
    category: TechCategory.Cloud,
  },
  { id: SkillIconsId.P5Js, name: "p5.js", category: TechCategory.Library },
  { id: SkillIconsId.Perl, name: "Perl", category: TechCategory.Language },
  {
    id: SkillIconsId.PowerShell,
    name: "PowerShell",
    category: TechCategory.Language,
  },
  { id: SkillIconsId.Php, name: "PHP", category: TechCategory.Language },
  {
    id: SkillIconsId.PhpStorm,
    name: "PhpStorm",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Pinia, name: "Pinia", category: TechCategory.Library },
  { id: SkillIconsId.Pkl, name: "PKL", category: TechCategory.Other },
  { id: SkillIconsId.Plan9, name: "Plan 9", category: TechCategory.Platform },
  {
    id: SkillIconsId.PlanetScale,
    name: "PlanetScale",
    category: TechCategory.Database,
  },
  { id: SkillIconsId.Pnpm, name: "pnpm", category: TechCategory.Other },
  {
    id: SkillIconsId.Postgres,
    name: "PostgreSQL",
    category: TechCategory.Database,
  },
  { id: SkillIconsId.Postman, name: "Postman", category: TechCategory.Other },
  {
    id: SkillIconsId.Ps,
    name: "Adobe PhotoShop",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Pr,
    name: "Adobe Premiere Pro",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Prisma, name: "Prisma", category: TechCategory.Library },
  {
    id: SkillIconsId.Processing,
    name: "Processing",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.Prometheus,
    name: "Prometheus",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Pug, name: "Pug", category: TechCategory.Language },
  {
    id: SkillIconsId.PyCharm,
    name: "PyCharm",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Py, name: "Python", category: TechCategory.Language },
  { id: SkillIconsId.PyTorch, name: "PyTorch", category: TechCategory.Library },
  { id: SkillIconsId.Qt, name: "Qt", category: TechCategory.Framework },
  { id: SkillIconsId.R, name: "R", category: TechCategory.Language },
  { id: SkillIconsId.RabbitMQ, name: "RabbitMQ", category: TechCategory.Other },
  {
    id: SkillIconsId.Rails,
    name: "Ruby on Rails",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.RaspberryPi,
    name: "Raspberry Pi",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.React, name: "React", category: TechCategory.Framework },
  {
    id: SkillIconsId.ReactiveX,
    name: "ReactiveX",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.RedHat, name: "Red Hat", category: TechCategory.Platform },
  { id: SkillIconsId.Redis, name: "Redis", category: TechCategory.Database },
  { id: SkillIconsId.Redux, name: "Redux", category: TechCategory.Library },
  {
    id: SkillIconsId.Regex,
    name: "Regular Expressions (Regex)",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Remix, name: "Remix", category: TechCategory.Framework },
  { id: SkillIconsId.Replit, name: "Replit", category: TechCategory.Platform },
  {
    id: SkillIconsId.Rider,
    name: "JetBrains Rider",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.RobloxStudio,
    name: "Roblox Studio",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Rocket, name: "Rocket", category: TechCategory.Framework },
  {
    id: SkillIconsId.RollupJS,
    name: "Rollup.js",
    category: TechCategory.BuildTool,
  },
  {
    id: SkillIconsId.Ros,
    name: "Robot Operating System (ROS)",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Ruby, name: "Ruby", category: TechCategory.Language },
  { id: SkillIconsId.Rust, name: "Rust", category: TechCategory.Language },
  { id: SkillIconsId.Sass, name: "Sass", category: TechCategory.Language },
  {
    id: SkillIconsId.Spring,
    name: "Spring Framework",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Sqlite, name: "SQLite", category: TechCategory.Database },
  {
    id: SkillIconsId.StackOverflow,
    name: "Stack Overflow",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.StyledComponents,
    name: "Styled Components",
    category: TechCategory.Library,
  },
  {
    id: SkillIconsId.Sublime,
    name: "Sublime Text",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Supabase,
    name: "Supabase",
    category: TechCategory.Database,
  },
  { id: SkillIconsId.Scala, name: "Scala", category: TechCategory.Language },
  {
    id: SkillIconsId.Sklearn,
    name: "scikit-learn",
    category: TechCategory.Library,
  },
  {
    id: SkillIconsId.Selenium,
    name: "Selenium",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Sentry, name: "Sentry", category: TechCategory.Other },
  {
    id: SkillIconsId.Sequelize,
    name: "Sequelize",
    category: TechCategory.Library,
  },
  {
    id: SkillIconsId.SketchUp,
    name: "SketchUp",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Solidity,
    name: "Solidity",
    category: TechCategory.Language,
  },
  {
    id: SkillIconsId.SolidJS,
    name: "SolidJS",
    category: TechCategory.Framework,
  },
  { id: SkillIconsId.Svelte, name: "Svelte", category: TechCategory.Framework },
  {
    id: SkillIconsId.Svg,
    name: "SVG (Scalable Vector Graphics)",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Swift, name: "Swift", category: TechCategory.Language },
  {
    id: SkillIconsId.Symfony,
    name: "Symfony",
    category: TechCategory.Framework,
  },
  {
    id: SkillIconsId.Tailwind,
    name: "Tailwind CSS",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Tauri, name: "Tauri", category: TechCategory.Platform },
  {
    id: SkillIconsId.TensorFlow,
    name: "TensorFlow",
    category: TechCategory.Library,
  },
  {
    id: SkillIconsId.Terraform,
    name: "Terraform",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.ThreeJS,
    name: "Three.js",
    category: TechCategory.Library,
  },
  { id: SkillIconsId.Twitter, name: "Twitter", category: TechCategory.Other },
  { id: SkillIconsId.Ts, name: "TypeScript", category: TechCategory.Language },
  { id: SkillIconsId.Ubuntu, name: "Ubuntu", category: TechCategory.Platform },
  { id: SkillIconsId.Unity, name: "Unity", category: TechCategory.Platform },
  {
    id: SkillIconsId.Unreal,
    name: "Unreal Engine",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.V, name: "V", category: TechCategory.Language },
  { id: SkillIconsId.Vala, name: "Vala", category: TechCategory.Language },
  { id: SkillIconsId.Vercel, name: "Vercel", category: TechCategory.Platform },
  { id: SkillIconsId.Vim, name: "Vim", category: TechCategory.Other },
  {
    id: SkillIconsId.VisualStudio,
    name: "Visual Studio",
    category: TechCategory.Platform,
  },
  { id: SkillIconsId.Vite, name: "Vite", category: TechCategory.BuildTool },
  { id: SkillIconsId.Vitest, name: "Vitest", category: TechCategory.Other },
  {
    id: SkillIconsId.Vscode,
    name: "Visual Studio Code",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Vscodium, name: "VSCodium", category: TechCategory.Other },
  { id: SkillIconsId.Vue, name: "Vue.js", category: TechCategory.Framework },
  { id: SkillIconsId.Vuetify, name: "Vuetify", category: TechCategory.Library },
  {
    id: SkillIconsId.Wasm,
    name: "WebAssembly (WASM)",
    category: TechCategory.Other,
  },
  {
    id: SkillIconsId.Webflow,
    name: "Webflow",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.Webpack,
    name: "Webpack",
    category: TechCategory.BuildTool,
  },
  {
    id: SkillIconsId.WebStorm,
    name: "WebStorm",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.WindiCSS,
    name: "Windi CSS",
    category: TechCategory.Library,
  },
  {
    id: SkillIconsId.Windows,
    name: "Windows",
    category: TechCategory.Platform,
  },
  {
    id: SkillIconsId.WordPress,
    name: "WordPress",
    category: TechCategory.Other,
  },
  { id: SkillIconsId.Workers, name: "Workers", category: TechCategory.Other },
  { id: SkillIconsId.Xd, name: "Adobe XD", category: TechCategory.Other },
  { id: SkillIconsId.Yarn, name: "Yarn", category: TechCategory.Other },
  { id: SkillIconsId.Yew, name: "Yew", category: TechCategory.Framework },
  { id: SkillIconsId.Zig, name: "Zig", category: TechCategory.Language },
];
